version: '3'
services:
  db:
    image: 'postgres:latest'
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=onsen
      - POSTGRES_PASSWORD=onsen-db-password
      - POSTGRES_DB=onsen_dev
#  api:
#    build:
#      context: './api'
#      dockerfile: Dockerfile.dev
#    volumes:
#      - /app/node_modules
#      - ./api:/app
#    ports:
#      - '8080:3000'
#    environment:
#      - DB_HOST=db
#      - DB_USER=postgres
#      - DB_DATABASE_NAME=onsen_dev
#      - DB_PASSWORD=onsen-db-password
#      - DB_PORT=5432
